name: ubuntu
run-name: ubuntu-test
on: [ push ]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list.d/ubuntu.sources
          apt update
          apt install -y libmruby-dev
          mkdir build && cd build
          cmake ..
          cmake --build . --target mrubypp_test
          ./mrubypp_test
      - run: echo "🍏 This job's status is ${{ job.status }}."